ibillmaker_hub_core_homepage:
    path:     /hello/{name}
    defaults: { _controller: IbillmakerHubCoreBundle:Default:index }
    
ibillmaker_hub_core_get_userdetails:
    path: iauser/getuserdetails/{id} 
    defaults: { _controller: IbillmakerHubCoreBundle:IAUser:getUserDetails }

ibillmaker_hub_core_check_user_name:
    path: iauser/checkusername/{userName}/{id} 
    defaults: { _controller: IbillmakerHubCoreBundle:IAUser:checkUserName }

ibillmaker_hub_core_save_user_details:
    path: iauser/saveuserdetails 
    defaults: { _controller: IbillmakerHubCoreBundle:IAUser:saveUserDetails }
    
#    Address routes

ibillmaker_hub_core_create_address:
    path: iauser/address/new
    defaults: { _controller: IbillmakerHubCoreBundle:IAAddress:createAddress }
