parameters:
    ibillmaker_hub_core.user.provider.class: Ibillmaker\Hub\CoreBundle\Security\UserProvider
    ibillmaker_hub_core.user.repository.class: Ibillmaker\Hub\CoreBundle\Security\UserRepository
    ibillmaker_hub_core.router.provider.class: Ibillmaker\Hub\CoreBundle\Repository\RouterProvider
    ibillmaker_hub_core.form.type.class: Ibillmaker\Hub\CoreBundle\Form\Type\RegistrationFormType    
    ibillmaker_hub_core.user.entity.class: Ibillmaker\Hub\CoreBundle\Entity\User
    
    # ibillmaker custom service classes
    ibillmaker_hub_core.service.user.class: Ibillmaker\Hub\CoreBundle\Service\UserService
    ibillmaker_hub_core.service.responseCreate.class: Ibillmaker\Hub\CoreBundle\Service\ResponseCreateService
    

services:
    ibillmaker_hub_core_user_provider:
        class: %ibillmaker_hub_core.user.provider.class%
        arguments: ["@service_container"]
        
    sylius.user.registration.form.type:
        class: %ibillmaker_hub_core.form.type.class%
        tags: 
             -  { name: form.type , alias : sylius_user_registration}
        arguments: [%ibillmaker_hub_core.user.entity.class%]
        
    ibillmaker_hub_core_route_provider:
        class: %ibillmaker_hub_core.router.provider.class%
    
            
    ibillmaker.hub.core.service.user:
        class: %ibillmaker_hub_core.service.user.class%
        arguments: ["@service_container"]
        
    ibillmaker.hub.core.service.response_create:
        class: %ibillmaker_hub_core.service.responseCreate.class%
        arguments: ["@service_container"]
        